//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFirstEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIANGDAY
    {
        public string MALOP { get; set; }
        public string MAMH { get; set; }
        public Nullable<int> HOCKY { get; set; }
        public Nullable<int> NAM { get; set; }
        public string TUNGAY { get; set; }
        public string DENNGAY { get; set; }
    }
}
